# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(600, 450)
        self.userNameLine = QtWidgets.QLineEdit(login)
        self.userNameLine.setGeometry(QtCore.QRect(200, 100, 311, 31))
        self.userNameLine.setObjectName("userNameLine")
        self.usernameLabel = QtWidgets.QLabel(login)
        self.usernameLabel.setGeometry(QtCore.QRect(70, 90, 121, 41))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(login)
        self.passwordLabel.setGeometry(QtCore.QRect(70, 160, 131, 41))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLine = QtWidgets.QLineEdit(login)
        self.passwordLine.setGeometry(QtCore.QRect(200, 170, 311, 31))
        self.passwordLine.setObjectName("passwordLine")
        self.frame = QtWidgets.QFrame(login)
        self.frame.setGeometry(QtCore.QRect(30, 260, 521, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.forgot_passwordButton = QtWidgets.QPushButton(self.frame)
        self.forgot_passwordButton.setGeometry(QtCore.QRect(0, 20, 201, 61))
        self.forgot_passwordButton.setObjectName("forgot_passwordButton")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(240, 20, 121, 61))
        self.exitButton.setObjectName("exitButton")
        self.exitButton_2 = QtWidgets.QPushButton(self.frame)
        self.exitButton_2.setGeometry(QtCore.QRect(380, 20, 121, 61))
        self.exitButton_2.setObjectName("exitButton_2")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Dialog"))
        self.usernameLabel.setText(_translate("login", "username:"))
        self.passwordLabel.setText(_translate("login", "password:"))
        self.forgot_passwordButton.setText(_translate("login", "forgot_password?"))
        self.exitButton.setText(_translate("login", "enter"))
        self.exitButton_2.setText(_translate("login", "exit"))
